
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.4
  creationTimestamp: null
  name: ciliumpodippools.cilium.io
spec:
  group: cilium.io
  names:
    categories:
    - cilium
    kind: CiliumPodIPPool
    listKind: CiliumPodIPPoolList
    plural: ciliumpodippools
    shortNames:
    - cpip
    singular: ciliumpodippool
  scope: Cluster
  versions:
  - name: v2alpha1
    schema:
      openAPIV3Schema:
        description: CiliumPodIPPool defines an IP pool that can be used for pooled
          IPAM (i.e. the multi-pool IPAM mode).
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              cidr:
                type: string
              ipv4:
                description: IPv4 specifies the IPv4 CIDRs and mask sizes of the pool
                properties:
                  cidrs:
                    description: CIDRs is a list of IPv4 CIDRs that are part of the
                      pool.
                    items:
                      description: PoolCIDR is an IP pool CIDR.
                      format: cidr
                      type: string
                    minItems: 1
                    type: array
                  maskSize:
                    description: MaskSize is the mask size of the pool.
                    maximum: 32
                    minimum: 1
                    type: integer
                required:
                - cidrs
                - maskSize
                type: object
              ipv6:
                description: IPv6 specifies the IPv6 CIDRs and mask sizes of the pool
                properties:
                  cidrs:
                    description: CIDRs is a list of IPv6 CIDRs that are part of the
                      pool.
                    items:
                      description: PoolCIDR is an IP pool CIDR.
                      format: cidr
                      type: string
                    minItems: 1
                    type: array
                  maskSize:
                    description: MaskSize is the mask size of the pool.
                    maximum: 128
                    minimum: 1
                    type: integer
                required:
                - cidrs
                - maskSize
                type: object
              subnet-id:
                type: string
                x-kubernetes-validations:
                  - message: subnet-id is immutable spec
                    rule: self == oldSelf
              vpc-id:
                type: string
            type: object
          status:
            description: IPPoolStatus describe the status of the nodes which uses
              the pool
            properties:
              items:
                additionalProperties:
                  description: ItemSpec describe the status of the node which uses
                    the pool
                  properties:
                    phase:
                      type: string
                    status:
                      type: string
                  type: object
                description: Items is a list of CiliumPodIPPools.
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
